---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cluster-issuer
spec:
    acme:
        solvers:
            - dns01:
                webhook:
                    solverName: hetzner
                    groupName: acme.hetzner.com
                    config:
                        tokenSecretKeyRef:
                            name: hetzner
                            key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: wildcard-fingol-pro
    namespace: traefik-ext
spec:
    secretName: hetzner-secret
    dnsNames:
        - '*.fingol.pro'
    issuerRef:
        name: cluster-issuer
        kind: ClusterIssuer
