---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    email: admin@fingol.pro
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: tls.key
    solvers:  
      - dns01:
          webhook:
            solverName: hetzner
            groupName: acme.hetzner.com
            config:
              tokenSecretKeyRef:
                name: hetzner-secret
                key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-fingol-pro
  namespace: default
spec:
  secretName: hetzner-secret
  dnsNames:
    - '*.fingol.pro'
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
