creation_rules:
  # All other secrets - encrypt everything in data/stringData
  - path_regex: flux/.*\.yaml|flux/.*\.yml
    encrypted_regex: ^(data|stringData|users)$
    age: >-
      age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
