- op: replace
  path: /spec/template/spec/initContainers/0/env
  value:
    - name: NETBIRD_STORE_CONFIG_ENGINE
      value: "sqlite"
    - name: NETBIRD_SIGNAL_URI
      value: "netbird.fingol.pro:443"
    - name: NETBIRD_SIGNAL_PROTOCOL
      value: "https"
    - name: NETBIRD_STUN_URI
      value: "stun:netbird.fingol.pro:3478"
    - name: NETBIRD_IDP_MANAGER_TYPE
      value: "oidc"
      value: "netbird.fingol.pro"

    - name: NETBIRD_RELAY_DOMAIN
      value: "netbird.fingol.pro"
    - name: NETBIRD_RELAY_PORT
      value: "443"
    - name: NETBIRD_RELAY_AUTH_SECRET
      valueFrom:
        secretKeyRef:
          name: netbird-secret
          key: netbird-relay-secret-key

    - name: NETBIRD_COTURN_USERNAME
      valueFrom:
        secretKeyRef:
          name: netbird-coturn-auth-secret
          key: username
    - name: NETBIRD_COTURN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: netbird-coturn-auth-secret
          key: password

    - name: CUSTOM_NETBIRD_AUTH_ISSUER
      value: "https://auth.fingol.pro"
    - name: CUSTOM_NETBIRD_AUTH_KEYS_LOCATION
      value: "https://auth.fingol.pro/jwks.json"
    - name: NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT
      value: "https://auth.fingol.pro/.well-known/openid-configuration"

    - name: CUSTOM_NETBIRD_PKCE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: netbird-secret
          key: netbird-pkce-secret-key
    - name: CUSTOM_NETBIRD_PKCE_AUTH_ENDPOINT
      value: "https://auth.fingol.pro/api/oidc/authorization"
    - name: CUSTOM_NETBIRD_PKCE_TOKEN_ENDPOINT
      value: "https://auth.fingol.pro/api/oidc/token"

- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - --log-level
    - info
    - --log-file
    - console
    - --disable-anonymous-metrics
    - "true"
    - --dns-domain
    - nb.fingol.pro
    - --single-account-mode-domain
    - nb.fingol.pro
