- op: replace
  path: /spec/template/spec/initContainers/0/env
  value:
    - name: NETBIRD_SIGNAL_URI
      value: "netbird.fingol.pro:9443"
    - name: NETBIRD_SIGNAL_PROTOCOL
      value: "https"
    - name: NETBIRD_STUN_URI
      value: "stun:netbird.fingol.pro:3478"
    - name: NETBIRD_TURN_URI31
      value: "turn:netbird.fingol.pro:3478"
    - name: NETBIRD_IDP_MANAGER_TYPE
      value: "oidc"
    - name: NETBIRD_RELAY_DOMAIN
      value: "netbird.fingol.pro"
    - name: NETBIRD_RELAY_PORT
      value: "33080"

    - name: CUSTOM_NETBIRD_AUTH_ISSUER
      value: "https://auth.fingol.pro"
    - name: CUSTOM_NETBIRD_AUTH_KEYS_LOCATION
      value: "https://auth.fingol.pro/jwks.json"
    - name: NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT
      value: "https://auth.fingol.pro/.well-known/openid-configuration"

    - name: CUSTOM_NETBIRD_PKCE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: netbird-secret
          key: netbird-pkce-secret-key
    - name: CUSTOM_NETBIRD_PKCE_AUTH_ENDPOINT
      value: "https://auth.fingol.pro/api/oidc/authorization"
    - name: CUSTOM_NETBIRD_PKCE_TOKEN_ENDPOINT
      value: "https://auth.fingol.pro/api/oidc/token"

