apiVersion: v1
kind: Secret
metadata:
    name: netbird-secret
type: Opaque
stringData:
    netbird-relay-secret-key: ENC[AES256_GCM,data:x3O8UXfVVWiFLjJRkur9D+JkySRcZF0QOug06ofM,iv:sSkM830Ef5d0wo2rmeV0BJ8zybdf+jV7l5DPpj3w4D4=,tag:EFUhMqhGw5EXSRVJSb/B/w==,type:str]
    netbird-pkce-secret-key: ENC[AES256_GCM,data:cN0FaJt2nGvGKh0iWdFXF7KB+mE4jA==,iv:ehRDtiF7ifQ7V0tj/fCk5pPb3tA7K8C3kG+DBVFMo8g=,tag:MTCAkZA/cNDOxTvWUUMj7g==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMGZZVmUvelNxZDhTU24z
            NldQUFduZmhKZDZoZWVoQjJJeTdnSUx2QWxnCnY3alhHQWNmT1VCaUs0WEVjTEVZ
            MU4wdlhWTkdpZk05WHkyUGdPM0JndTQKLS0tIGhRV2lLYWRFaXpqSDV3UWJ5Wjh0
            RERyR2lacEpzTUg1Sk52M1hXOUM5cmMKNv39my2/V0kicSHgwJhr+D2c1o0JMh2G
            +9MvpHUFI0D0MPE5dPWMHqJuQMZWePin94tl/aFD6hASZXp9S5amLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:33:42Z"
    mac: ENC[AES256_GCM,data:gzleewSmEnEQ+KX/RNw2PHdJDTr84Qrqbb1TU7Q0rQqT37hjg1GyFkFco2EZY3FnK87pv5DNpeX6AeRv+deNYJQPPn4yamBELUzymG3rQsW3dZejs9zGmqw/mxt5hOodkgxU1N7g4goqeBJWxmoK/kLALpsX8RiUF504067R4dw=,iv:JaNyqfAFYENrzUhl9TvZEuGHRRpNuh1uVmlGvyVdEkg=,tag:ahbdKUXYodUdkfhXShmcZw==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
