apiVersion: v1
kind: Secret
metadata:
    name: netbird-secret
type: Opaque
stringData:
    netbird-relay-secret-key: ENC[AES256_GCM,data:x3O8UXfVVWiFLjJRkur9D+JkySRcZF0QOug06ofM,iv:sSkM830Ef5d0wo2rmeV0BJ8zybdf+jV7l5DPpj3w4D4=,tag:EFUhMqhGw5EXSRVJSb/B/w==,type:str]
    netbird-pkce-secret-key: ENC[AES256_GCM,data:qZmnPRYfm+r/3N5iRQ0bG7eG45jhPU11Xc0fRteHKn2RmDStjTZGtKnRlfuxz6aepNkKoo+p7qpWyfUZhujndg==,iv:12wfrcciSOFRDmYiUgyREXuNXSt9lIfNeWPjAIgAf1k=,tag:M0wpe1z0JdKj6yM4D3bhuw==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMGZZVmUvelNxZDhTU24z
            NldQUFduZmhKZDZoZWVoQjJJeTdnSUx2QWxnCnY3alhHQWNmT1VCaUs0WEVjTEVZ
            MU4wdlhWTkdpZk05WHkyUGdPM0JndTQKLS0tIGhRV2lLYWRFaXpqSDV3UWJ5Wjh0
            RERyR2lacEpzTUg1Sk52M1hXOUM5cmMKNv39my2/V0kicSHgwJhr+D2c1o0JMh2G
            +9MvpHUFI0D0MPE5dPWMHqJuQMZWePin94tl/aFD6hASZXp9S5amLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T23:46:36Z"
    mac: ENC[AES256_GCM,data:SmwjvDEZIRXUQ8QLHyiIPdan2NrKdMWshuMaS7W8cefvkusAUrKUUG26MOplQSYeTDkdgh5WBFOFp/K2AR6wLOIC8zrUHsbugaW3iZNY3fd6jjB+LB9RArkgDJedBDTu3a/VZqJrwsTy4xYB/MMH8kdzTyupAAxR32zcgcU54Is=,iv:PAaWWd47XJSV9SqTcdyMvjGKU4eCJBeiZ8yTVzrFWU0=,tag:QfGW/+SJ6AM9Igenhw5VQQ==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
