apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/cert-secrets/ext
  prune: false  # Don't delete secrets if removed from git
  timeout: 2m0s
  decryption:
    provider: sops
    secretRef:
      name: sops-age
