apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PPHnim0kRh1LrpKFOb0sBCiX2SE=,iv:LBIfYmjVixQ+JUodj+zTAD1IKHDC3rT5qqhBcCFgFoI=,tag:IURyhJsPnn6Dds3h46xx7Q==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SWlCQ1lZUk16MXFmWGVy
            VWw3YXZqdDA5S3NWdXgzS0pDMnJDRjl5YkhJCnNra0FoQ3hEOE0xUi9lTll6NVJ3
            MkxnVkZoL0hoeGdYSUFrLzBqbkNmdkkKLS0tIGdld1NRNzdob01hKzBuZENHb1JD
            UEpCUklURmgwdWtCRlVtUnpLN2hORFkKsESJlrgV9EniqwRH/7p6dNf2ki5HU6QF
            gX4jG6g8i5eJNo9LJ9/zZtnE7HG/Z0eecK/ULhoRivDS2kcxbjzQIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T13:02:29Z"
    mac: ENC[AES256_GCM,data:DqtBcMAEJu4egDPG+sY9UUQpcZu4D8Mh8oEgjGXhcCV+tKf7sEKm2EavUmkz3cL6wUf7PLcTZrEC8rXEfs9qwEhGAMx5ma9MXQQIYA5d5qpJP0/+RlctAu1LE74zoSJQJfPr/5+4i5saR0/fuhYoCtylHeRakSJ8MX8skB8jZVI=,iv:Qu8QC6zvV2+GeqCPaix8o49+A+eN4pji3bjGEtr5qgc=,tag:uVMSYaNz8T+5+xoOKCFOQw==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
