apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-client-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
