apiVersion: v1
kind: Secret
metadata:
    name: netbird-setup-key
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:Y9HKYYvLr64g9r1K6NeRN8FNSl/5ROHnWPiR5QwBDTfHhSOH,iv:XY5u0K6SNM20qL71t6lZuL3MUcYyOPqr7sp/kquorKo=,tag:sVJIatuDVa4Co5IbTazgZw==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbWlKbXFHUzJEY1FvMXdY
            MzB2czRnTHhKY2QycU9PSWVYV2lXVVh3Zm5nCndQUWh3eEJaRVJseVR0MXdCZXJL
            ZW40L0Yza0FzOTNCLzVGUjl2SUdBMkkKLS0tIGpmd29nRmpaNkhGNFpMWDdBUkRq
            ZWIweFFUem5mY3hvb3NaNTVzQVZwWjAKi4X21kltkkLW4mk1I12s6qzOYhaILZcC
            WyCbkccAUOdGg1HoHuW1AZeWZ91lwKcl6yUmMidP0HC5EsM0k50ERA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T18:09:05Z"
    mac: ENC[AES256_GCM,data:TD5d+PHEFr22f2d6iDgzzHVYkZa7QpAHCwoZ4BLNjmm/+GpxEV5sJD1qfLtyInryI/18/beDafMtowxhR45geM/bHaGS+eaITFalwrZMhZA8QU070VP5KzhmZ9oR6do/NfbnbFMLMZgvDqLQRXt5WGxJWbIZ6lr/p+F9pjheROE=,iv:WouasAwDKgoCTzuvqLvTuMGwbDiI00+80woIVZgLHX0=,tag:TNz+sCsz1MXgGJ1307gStw==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
