apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: authelia
  namespace: authelia
spec:
  parentRefs:
    - name: traefik
  rules:
    - matches:
        - path:
            type: Prefix
            value: /authelia
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              X-Forwarded-Proto: "https"
      backendRefs:
        - name: authelia
          port: 9091
