---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data-pvc
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
