apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:RDSB0tFtJrJDrGIuIJfFgso5u2lp5HP7nAzek9MOfhblFiU88LbznjHTLv9vcRsDEuhRBrjBanoULBtjYVGoCIyhXsqG1HNczl4c12qHP7+pW1zMgJQG9Qt+6yV5ORbgf4oz0Vu7n6mOJ0uLFv+XbUnAlUDZrfwF4BzhFrTRArk=,iv:oNsTSfdMj8lQ9VcFnQ1gTXU7KfZkqkf9UNcKdaGY6bw=,tag:qqAm7mcUcYa7xVovE7Ic4A==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:rnavEIXZxM508NPKKF5vMKAtKv4ClscLpabtR13TikfjuEGdPnI3FApDkLm1b3A76rdYFlxlWSIiA5ZjBJLAk8gpxj0rn98tnFSHbAYUPjQfT/zk6qGlEWEfdj/sL/wxzmtx1hrNx8vBy5cbP4aaVGbltc4MlwxnQ6qcFCSkTac=,iv:dqjOgTsZzZ6v18hQJADbIU9IClEwXsH6uGZZ+ba8XH4=,tag:/eZPsrt5eDGC2Bm7wZmC0Q==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:iYUpBIDEhlDsN5pRl7Qe+V4oSi+rBkw4riLLwDF9ZWj5y8+woq08mYfzKTcpvrS3fRbq+C+ihjV6Rr+115wpkeIhlwSPkeODS1jhi//4rXrF8YfmVKly9lcT9FoFI7TGcBg9buzFEb4po1B5IIP0Qo5cksC4L5K5R5TgBkB7h4w=,iv:az/ehY/+MN96TXeIrtOADcIWkr74VDrDSlE6wWU7TiU=,tag:JXhY6GvQWCPu9HoiXyQCLw==,type:str]
    identity_provider.oidc.hmac_secret.key: ENC[AES256_GCM,data:xvtjpYFUyxM4E8dBI8NjjQgavGspGtI/J5ObbhmQFJ2C/bivShpwbD7D4Uwf68rucwoa1JHWAjV5ns4+mcrxE2k23y+A0KboLG2orMcz4mkGIWZBbmPirN5iq5v0AYUnsgOGWzwuQJcu5CPU4aW7QK4O1TqdqPwOSmaX8AFVQA8=,iv:QaCOK4FyXB38XppoAVZ/rMwXAxmKO5e4gdCIKNMLuLo=,tag:nnuJw8xF9gJD1VAv3+f8PQ==,type:str]
    identity_providers.clients.netbird.client_secret.key: ENC[AES256_GCM,data:+hHEJPOLS9THIkggBwcl9TIJzy5Gkg7pSB+2Ja2SuqFnjMSM66wuuJ4fa81oNSMoWJzKJBvZUWGe2/d99f69ApfIibYJiQpB1v8e5htYe+YpRz7KVeGezTLpOKn7o31i5QWbTAbzffgx2/UmDA0v1mB2FfMrSFMi4qRGsoa2C4c=,iv:/ygYOFYT7hPmxjgMYbYKDXC0kywaxTeknEwSkJapigQ=,tag:8Kg3v6gN4RIANCs3xPuIEQ==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdjRuakltMkgzNCtyVEEr
            OElwTDdOZXNOOStEbU1ubFhacUZhYnBJc1NzCmYrMFFvUzZvYUVGaE5BdXk0MkM0
            VldLbFpsNzU2dnFXM29iM3gwWWpwM2sKLS0tIDUwanZpekRFNExjc2VGeW9kS1lC
            NkRKckJNRXRzVkVreG1oOWdCMGJsMTAK9JpJbJF8RdyTViLfU5CcCQGEd8jHY9if
            K7EDi3ydbw3T/vSB/DiSDs4PeMN4Peq0E3Sry0zuSxSNsnrJPW0LSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T20:16:02Z"
    mac: ENC[AES256_GCM,data:65oWJ6MUsAi7gEudJhsJ96HO+zicExiH/BX9Lo3ZGC4NH82lIh/Pc9AvLZkSXLusozmwexYoMQ8B5q0WygvcWfRxD3R79zIfzgGluKQ6JYmiBRYGZXpSrEDf+OH6EFu1JIWrjNlKKS3D+F6+4d0krBMUAeCPBIB9R7iF4Kcrp7w=,iv:oJtLLFFdMelGYO2B5hl3rjt61eDeEY8KnsmGFpepMMU=,tag:lKMJGMf5IJywosjBeuILXg==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
