apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: authelia
type: Opaque
data:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:k09OvYw6xUvPZn35v9XLOYnAp90ZRSM6cA/GBDhNgcuhc7EJa7hFXkb8Wfx4OBYZX/5HzouWbW8B6wlDXAGjawS/CdxOXadXtQvZ+c8mXC30M/yfVv4bPqySYvb/W/FyVuT4mYAgpFA/DEDioHaMpUl8KJku/RllLt+A8buWujk=,iv:p8rg+4PtkbfIkeF/cdTvjN7VOuCQPxYKCrRndQI3BeE=,tag:WeueaQb5gPDAFIDr9+cXwQ==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:3qel1E/fWpdIJIxDbJONag29cgU19htEmtn/N4PnjHbDEe2DqPgIIA==,iv:dwDE9XLeXwhCPWSnxJkXlTniLk9ddPcu8Dj2cPGXSm4=,tag:0Na+R6B9gZnkdIufTeN7fQ==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:tALsRaeGpLzMBH0nXA6y61z5041INpE7UMWm941dxluxBzbBH5IKSw==,iv:XpDhBOLepYlzeUoMN6F07yWewVN05uRY6KhccKCgYlk=,tag:755AzoCxlerRKif13PzC3A==,type:str]
    identity_provider.oidc.hmac_secret.key: ENC[AES256_GCM,data:n/o42VZsqfkLyxBIarHAWSruNZUF0uM3wk3bb0f8L5U2j+pXBcOjrQ==,iv:BeGN3/RaiFi6pxOUk8OLiG00oflv9Y/3nUYAGVsS+4I=,tag:SXLTUrj8l1DfE4Hg0/rxgQ==,type:str]
    identity_providers.clients.netbird.client_secret.key: ENC[AES256_GCM,data:2HL59Isg64vD5i0AKcUzyErHS3PGrLEAnbBelpiBg2IqTUdjPQh3AtuFnd2HeUTXlu6hkgCfBc1oXWgEvVEYWA==,iv:yA08wn64GQajpK4s66SljO9YzWUCFMC3K1Zyez86o4A=,tag:QbdpH8edOtN3DupvQeDP6g==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdjRuakltMkgzNCtyVEEr
            OElwTDdOZXNOOStEbU1ubFhacUZhYnBJc1NzCmYrMFFvUzZvYUVGaE5BdXk0MkM0
            VldLbFpsNzU2dnFXM29iM3gwWWpwM2sKLS0tIDUwanZpekRFNExjc2VGeW9kS1lC
            NkRKckJNRXRzVkVreG1oOWdCMGJsMTAK9JpJbJF8RdyTViLfU5CcCQGEd8jHY9if
            K7EDi3ydbw3T/vSB/DiSDs4PeMN4Peq0E3Sry0zuSxSNsnrJPW0LSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T19:36:24Z"
    mac: ENC[AES256_GCM,data:hPnlj1D6Df2EJzu8lKoSU1K6DIjwPSYQGfc4Ydy/zxsWKgSbB6Od4V7McnldDG+5lKmRuTK1MYxUsHGaetUCbvp6GyQXBXb2fE53DRHa2FugDzmDPEVoJOMlS6E7vjZVQlXoWwk6e+rlXtwBbrC27yxN+ZVhI4QajgW4oZMMQQI=,iv:NFzeU0FahcBncYcRl4H9kNHaIIOdjkfHZK9PngVlUps=,tag:GD728QhqxNOWdVa1ZiKf1A==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
