apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-config-pvc-backup
spec:
  # The PVC to be backed up
  sourcePVC: config-pvc
  trigger:
    # Take a backup every night at 01:00 AM
    schedule: "0 1 * * *"
  restic:
    pruneIntervalDays: 14
    repository: restic-config
    copyMethod: Direct
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyfin-config-pvc-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config
    copyMethod: Direct
    destinationPVC: config-pvc
    capacity: 5Gi
    accessModes:
      - ReadWriteOnce
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
