apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-lapi-secrets
    labels:
        k8s-app: crowdsec
        type: lapi
        version: v1
type: Opaque
stringData:
    csLapiSecret: null
    registrationToken: ENC[AES256_GCM,data:+a8I036zhTnUX3aeZgXbGkKPNatDBznpeqoe8ZRFthHCLxlFGeTaBpKwcd1fmjPE0WjYmjk9LFlMaTEBhiOdRw==,iv:7FLp9oWDa4tC54727gNX3qP18tFINsVD0sobBRFMLGk=,tag:/sETH5ZKqaiTkZp4CWNRNA==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSEUycFluUHFhN01iYVFw
            aVV4VS9uMWMzQ0xqQ0lsRm5qL29YY0RiRGwwClR6YXAzWUd3UUFLb1ZEK25QZHh6
            bEx2dENTQlo2amxhdUhnRDg0MENJdDAKLS0tIGN4aXprK0VHdDduYmpQN3ZTalIx
            VDBYdlhTRnNZMmJnaXdJVXVUcEJxNnMKvW9Vdymp5hIW8hX7ujHFbFkBhJWluqnl
            U9FyHYr8gp6sBnaVxjDcgtxK4rR989Q5GZUaQu49JdR98M+nqEr+Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T17:10:57Z"
    mac: ENC[AES256_GCM,data:UUwpPMYxwH9meJEkiNucufps2v/i/qv5owAGb1dF06huMCnb0cBBS7PltAJ1fnNdbe73i0LDttRTXrk6iaymEWRbKPDLfQSt750xjQSuc/Ys82wBaUHa7NEbm/KlLPaksT/+KKgINi8Ozw4oE/jiik0XmhKtIlDkxozbJHzD2iU=,iv:+Zp5GNgOf1EOjYM3KHvfplkIdxJxLMdSrMxc/uJIvJU=,tag:TvjhPYvbGTBG6oR52l1/qg==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
