apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-lapi-secrets
    labels:
        k8s-app: crowdsec
        type: lapi
        version: v1
type: Opaque
stringData:
    csLapiSecret: ENC[AES256_GCM,data:xhVjLTwH5zV+2QZI94v41u/+7WMhnPPwUa0ILAdipOikT6WpZ0Ix29QrAixSvIRlLSk84vH10ceO4IsMdr7g5Q==,iv:NuGAcNTVh24rELDmRSetaCn6FCL847m/HuEKg2+Nt5E=,tag:pyzV14ZzefsKzX8wPGImBQ==,type:str]
    registrationToken: ENC[AES256_GCM,data:+a8I036zhTnUX3aeZgXbGkKPNatDBznpeqoe8ZRFthHCLxlFGeTaBpKwcd1fmjPE0WjYmjk9LFlMaTEBhiOdRw==,iv:7FLp9oWDa4tC54727gNX3qP18tFINsVD0sobBRFMLGk=,tag:/sETH5ZKqaiTkZp4CWNRNA==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSEUycFluUHFhN01iYVFw
            aVV4VS9uMWMzQ0xqQ0lsRm5qL29YY0RiRGwwClR6YXAzWUd3UUFLb1ZEK25QZHh6
            bEx2dENTQlo2amxhdUhnRDg0MENJdDAKLS0tIGN4aXprK0VHdDduYmpQN3ZTalIx
            VDBYdlhTRnNZMmJnaXdJVXVUcEJxNnMKvW9Vdymp5hIW8hX7ujHFbFkBhJWluqnl
            U9FyHYr8gp6sBnaVxjDcgtxK4rR989Q5GZUaQu49JdR98M+nqEr+Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T18:01:34Z"
    mac: ENC[AES256_GCM,data:NhHJzjPC0yakSjEDYLGMc/sLShhq8rXb1JVmxw3UyUR3HBSQ5CE9U1tZouHm9Ex2zMrlHKg9Ueg6xeHyT2R/ut0X/FhcAW154DTg2REPuIUjXDbjR1zKLBZU2MxqlMekY2uem6Ea7qZmXbbxLgSOuTDWFMwVwf/fG3NVBIRYzQI=,iv:jB0eoplFYadIUhGRj1fkibUJIUcEbtZ+7yQLhHfXBRQ=,tag:RRv+zsosS3iBwdiA1Hv43Q==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
