---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koito-pvc
  labels:
    app.kubernetes.io/name: koito
    app.kubernetes.io/instance: koito
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koito-db-pvc
  annotations:
    k8up.io/backup: "true"
  labels:
    app.kubernetes.io/name: koito
    app.kubernetes.io/instance: koito
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
