apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: navidrome-pvc-backup
spec:
  # The PVC to be backed up
  sourcePVC: navidrome-data-pvc
  trigger:
    # Take a backup every 30 minutes
    schedule: "*/30 * * * *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: restic-config
    # Retention policy for backups
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    # Direct copy - backup directly from the PVC without cloning
    # Works with any storage class, no CSI features required
    copyMethod: Direct
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    #storageClassName: my-sc-name
    # The VSC to use if the copy method is Snapshot (default if omitted)
    #volumeSnapshotClassName: my-vsc-name
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: navidrome-pvc-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: restic-config
    # Use an existing PVC, don't provision a new one
    destinationPVC: navidrome-data-pvc
    copyMethod: Direct
