apiVersion: v1
kind: Namespace
metadata:
  name: navidrome
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/service: navidrome
    app.kubernetes.io/instance: navidrome
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 4533
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: navidrome
    app.kubernetes.io/instance: navidrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  labels:
    app.kubernetes.io/instance: navidrome
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: navidrome
      app.kubernetes.io/instance: navidrome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: navidrome
        app.kubernetes.io/instance: navidrome
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: navidrome
          image: "deluan/navidrome:0.59.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: ND_ENABLESHARING
              value: "false"
            - name: ND_ENABLETRANSCODINGCONFIG
              value: "true"
            - name: ND_LOGLEVEL
              value: info
            - name: ND_MUSICFOLDER
              value: /music
            - name: ND_PROMETHEUS_ENABLED
              value: "false"
            - name: ND_SESSIONTIMEOUT
              value: 24h
            - name: ND_LISTENBRAINZ_BASEURL
              value: "http://koito-svc.koito.svc.cluster.local:4110/apis/listenbrainz/1/" # connect to Koito
            - name: ND_DEFAULTTHEME
              value: "Spotify-ish"
            - name: ND_UILOGINBACKGROUNDURL
              value: "data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=" # the only way to disable rotating backgrounds
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: http
              containerPort: 4533
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4533
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4533
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 4533
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          volumeMounts:
            - name: navidrome-data
              mountPath: /data
            - name: navidrome-music
              mountPath: /music
      volumes:
        - name: navidrome-data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: navidrome-music
          persistentVolumeClaim:
            claimName: music-pvc
