---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  00-bootstrap.yaml: |
    version: 1
    metadata:
      name: bootstrap
    entries: []
#      - model: authentik_core.user
#        identifiers:
#          username: admin
#        attrs:
#          username: admin
#          name: Admin
