---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  notifications.yaml: |
    version: 1
    metadata:
      name: Notifications
    entries:
       - id: transport
         model: authentik_events.notificationtransport
         attrs:
           email_subject_prefix: 'authentik Notification: '
           email_template: email/event_notification.html
           mode: webhook
           name: ntfy
           send_once: true
           webhook_url: https://ntfy.vpn.fingol.pro/fF93fvAeoKe-auth
         identifiers:
           name: ntfy
         state: present
       
       - id: rule
         model: authentik_events.notificationrule
         attrs:
           group: !Find [authentik_core.group, [name, "authentik Admins"]]
           severity: alert
           transports:
             - !KeyOf transport
         identifiers:
           name: ntfy-rule
         state: present

       - id: notification_policy_binding_0
         model: authentik_policies.policybinding
         identifiers:
           order: 0
           policy:
             !Find [
               authentik_policies.policy,
               [name, "default-match-configuration-error"],
             ]
           target: !KeyOf rule

       - id: notification_policy_binding_1
         model: authentik_policies.policybinding
         identifiers:
           order: 1
           policy:
             !Find [
               authentik_policies.policy,
               [name, "default-match-policy-exception"],
             ]
           target: !KeyOf rule

       - id: notification_policy_binding_2
         model: authentik_policies.policybinding
         identifiers:
           order: 2
           policy:
             !Find [
               authentik_policies.policy,
               [name, "default-match-property-mapping-exception"],
             ]
           target: !KeyOf rule
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentic-blueprint-default-authentication-flow
  namespace: authentik
data:
  flow-default-authentication-flow.yaml: | 
    version: 1
    metadata:
      name: Default - Authentication flow (force TOTP)
    entries:
      - model: authentik_blueprints.metaapplyblueprint
        attrs:
          identifiers:
            name: Default - Password change flow
          required: false

      - model: authentik_flows.flow
        id: default-auth-flow
        identifiers:
          slug: default-authentication-flow
        attrs:
          designation: authentication
          name: Welcome
          title: Welcome
          authentication: none

      - model: authentik_stages_identification.identificationstage
        id: ident-stage
        identifiers:
          name: default-authentication-identification
        attrs:
          user_fields:
            - username
            - email

      - model: authentik_stages_password.passwordstage
        id: password-stage
        identifiers:
          name: default-authentication-password
        attrs:
          backends:
            - authentik.core.auth.InbuiltBackend
            - authentik.sources.kerberos.auth.KerberosBackend
            - authentik.sources.ldap.auth.LDAPBackend
            - authentik.core.auth.TokenBackend
          configure_flow: !Find [authentik_flows.flow, [slug, default-password-change]]

      - model: authentik_stages_authenticator_validate.authenticatorvalidatestage
        id: mfa-validate-stage
        identifiers:
          name: default-authentication-mfa-validation
        attrs:
          not_configured_action: configure
          configuration_stages:
            - !Find
              - authentik_stages_authenticator_totp.authenticatortotpstage
              - [name, default-authenticator-totp-setup]
          device_classes:
            - totp

      - model: authentik_stages_user_login.userloginstage
        id: login-stage
        identifiers:
          name: default-authentication-login

      - model: authentik_flows.flowstagebinding
        identifiers:
          order: 10
          stage: !KeyOf ident-stage
          target: !KeyOf default-auth-flow

      - model: authentik_flows.flowstagebinding
        id: password-binding
        identifiers:
          order: 20
          stage: !KeyOf password-stage
          target: !KeyOf default-auth-flow
        attrs:
          re_evaluate_policies: true

      - model: authentik_flows.flowstagebinding
        identifiers:
          order: 30
          stage: !KeyOf mfa-validate-stage
          target: !KeyOf default-auth-flow
        attrs:
          authentication: require_authenticated

      - model: authentik_flows.flowstagebinding
        identifiers:
          order: 100
          stage: !KeyOf login-stage
          target: !KeyOf default-auth-flow

      - model: authentik_policies_expression.expressionpolicy
        id: password-optional-policy
        identifiers:
          name: default-authentication-flow-password-stage
        attrs:
          expression: |
            flow_plan = request.context.get("flow_plan")
            if not flow_plan:
                return True
            return not hasattr(flow_plan.context.get("pending_user"), "backend")

      - model: authentik_policies.policybinding
        identifiers:
          order: 10
          target: !KeyOf password-binding
          policy: !KeyOf password-optional-policy
        attrs:
          failure_result: true
