apiVersion: v1
kind: Secret
metadata:
    name: slskd-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IcIMtEHPIhAtvYTHLMJ/lWHiL2cF,iv:xyVvMFbV38uZz5dbRRgVLdxO3yvODudM1wT8LOsn+0c=,tag:sbtFAb0poUTCNDSN66IEjg==,type:comment]
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:G3K8vZDQx0ileg0+qa4H+6n57Pw76A==,iv:1HvR92A3caE4sxSJ5W69X/eL0qVcFPgwcgFPfNY/5pk=,tag:npyCmAmzHSR+AOkdxNul2w==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:7mkpK9sxmj25z9X1kkbCiYvEm3LHBA==,iv:j6/h2ngZIDGrnnmJIsXU23cmJvlbDGLyM3h4IojuVPo=,tag:zyjK0thSKoq+T6IlXlLA2g==,type:str]
    #ENC[AES256_GCM,data:Hb4hJjQadfS5D5Y367b7KoBjweB5TWEG5suJQc2BIbXBcS3rOUM6PJFSmF9uopHBswjdLw==,iv:x3CPhaSnk/KoDQ/OcFQsHEs3M4CoZr6T1o9WSPKPs6U=,tag:1WYFt1k65w/fDTxPQhMWLg==,type:comment]
    #ENC[AES256_GCM,data:PM2A+guxv7MENnkh8vx1Md+fedqQccDQrmwEDQ==,iv:vJnkH+UReSmYwWPM0Sv7lYdAn2RALRs5KhAhgo7JsgY=,tag:FvFofQKsPyse5QEwuz3VmA==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:vE/+YFc9zw==,iv:SnDUfHjN5W2FqmA7P0INWih9lmA0/hNf4qDNClXQ0Ms=,tag:qUvzy9/x/GOcYl4LAKDoZg==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:Fjrfhw8AfXnq,iv:CeF4DPr9Nj2gRCJAY5ojWISjxfsbEJ1NYCIkNr7gR5I=,tag:93GsQLeR46udVoKO9HAFgQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:x6kpIgJmlfR8GXakubZFbUsWEFF+hofT2z0=,iv:e2EZGJ5ogmYEq8eyxvLAOD5bvgvC64iiHZnPuuMvOAc=,tag:bre/w3nuAwvnGu/oWWPmSw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:9jlkiTiVCj4KUt4=,iv:1CW7yG/Z27Cz8FTchZPdGEDc4sw0S9SdyGIbMc/1QWY=,tag:KlEDpHYBw622q3xAbbP8SA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:0y8wAPwwZ0hlnls=,iv:x2Wuez3lvBphep9Oi0pjz0LIeQwqcSp+6yMRP2hpmZs=,tag:7HRsWIJ4rR0UXgn6sH2vEQ==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNGhLODZ1OGVBcitBdGhu
            d2E0ZU1JaWpZUDQ3dTIxTnZMSkxGWTdXUVN3CkxpTWo3M2pVVXJjRlFHUGFmQm5S
            RFp5MEtyQWpJMmlDeVo2R21xdFhrdVkKLS0tIGhqYXJ6VlR0OGhIUFdUWWRnR3lq
            MDE5SnNKM3g3YU9oQU5yTGdLM25PNkEKli9dtAS8gRyP4vI9LgMTwR6bks6bUn5+
            5RHsDqZLqB3DxQP3M3+xMns6TfNiEb3yQ0wnXCRFjVVvwcXXnoxyDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T12:19:31Z"
    mac: ENC[AES256_GCM,data:CwOwbu/FZKltYFYCMqQgNbv3reKcziq++942P3omQf5Z5eoPrD4Y4NnDZD5jWMejKx2kP7fwKKcCQgRr2TBseGSOeExy5CKTXmb5d6bYn6zyMIblnjOYTJdGRRPCDuFL3cIU34xEoPKFgOW5JviNSvxNK0VNiFUPIc1IaHLzuRU=,iv:dMM/FW+INuPrX+Y9k4nyxFcrjUNkI9qyrl2eftCj8/Y=,tag:FocgzZprFgZIGZHrh/hulA==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
