apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-data-pvc
  annotations:
    k8up.io/backup: "true"
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
