apiVersion: v1
kind: Secret
metadata:
    name: restic-config
type: Opaque
stringData:
    #ENC[AES256_GCM,data:APEuCcc5uAwimxBHsRSoEkHPDA==,iv:cVDjrXLFYad7LsXt8qY58obKxIKtXqr0SeTaiVFPLEI=,tag:PhiBcz/S7VbIczgFQH15pA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:/KFlXy5KnZnVTLJ2U69HcWw0ITEbAp8z1udKcHG6T5HHLl1/kuvVUkuq4apX8LCj19mWuv6muLI=,iv:u/SMXTqgGVJ6MjVZXcizZhg4/6QSJtra+AW2lwZJjsM=,tag:GB1QkEizcfLbuXdMBtbK9A==,type:str]
    #ENC[AES256_GCM,data:y5t0Mt+ls2nsK0c+9BqVUfcTG2uIWI7nw+kDFYz3,iv:DDcgmEM5L03/lhjEffpVZ3j8IcOvfE86tk23rBjGXKs=,tag:E9QMFPpCSR2W7ZIiHqDb1A==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:OtjL+SSfXn4OqVvUHjJlnHGsltmkMECVGA==,iv:j9UEUH9lT6Ji0JE93NoLe3iJXLRrTOb2F7bqtlMDi/c=,tag:ChRqV9V7U77WjcCF6tAMwQ==,type:str]
    #ENC[AES256_GCM,data:D9q9t58gYu89E4ZscpO3F4nsXclmCIL83OdEya5dOGEeAkecrUbqpQg=,iv:s1SV/Ky4S8XVX30P5fGReZYIl8JWSDnf7R8BDUpvNyY=,tag:84sp0C6DfT1YrpilXuY8AA==,type:comment]
    #ENC[AES256_GCM,data:WqAmigvmPb4YgVXR9xhXJEC0V2T5BqavQzQIKjnVJLt42ohXN4gxcAJ522Ry9OjHtalR3Cw8qyvNrqTbRLhapo+n8OfoSg==,iv:Vz4rFWGXHnJ6L5s+msLt+SYAYDAe0vw6qSmNSRwszIs=,tag:8JbUeeNkQEfGMhJJ+opU4g==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n2jMdVNk,iv:KOCqN45O0eoDH6zmQYwaWlGF2fiyN603o3egq+9EHrw=,tag:sn94J+LM0BOgM8pg/MerKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/kl3DVtUJZM=,iv:gOcKQK3GG/17h19b+1WU0uCYdLztS4Gk+nm65zooGl0=,tag:Tn30LzgA9800bAqDL96Znw==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbHNyRjFLYUw3MjJWeFMz
            YkJxTVNxR0w3djVpckJzSUpGRE5qNGQxZDJ3ClhINW01a0pUWkV1U1Bmc3ZEdUJm
            YkFPT2lMclJyZkpYdmFuNk9LQzUrWmsKLS0tIHJieHhXN3YvSG5EN2VQaVNDQnVs
            KytmMWpsdkovY1VtY0hTSWtOVmttdzQKtOtv4o6p1BsxfQQTGUfI0gG5L7kbfzat
            IF2tzS0CBxDEogSJTMC/DwQ47/c+Dnn7eBViKY2JTmR2aDz01i+qDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T22:27:57Z"
    mac: ENC[AES256_GCM,data:KsDfO1Z5WkMPoEqjjZRQFKZ8TCh/LDd2RodIYVzakBJFKFzRwYi2MeYiaSXjchCTqEAz7OJHk9733H/KiR/3LBkXglUtMRNfRQG6co0Hl73693RgYGN1xw8YrLlMFq3yfrq79JKzEg2dFha65/jIxjAKdlNFnhOmXAZqcrYSuqw=,iv:yd3OmSGZO0ku+ZWcNtVPz6EVJ7EJ2KBDRH9qmIEGPSY=,tag:GI69glJXwZWMwUJGCoTrmg==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
