apiVersion: v1
kind: Secret
metadata:
    name: restic-config
type: Opaque
stringData:
    RESTIC_REPOSITORY: PATCH_ME
    RESTIC_REST_USERNAME: ENC[AES256_GCM,data:c7at14kybw==,iv:iBlB7FzvKpYtLiquAJwsAK5t3GTOHJD9qLjMPn3/Kio=,tag:9xgw0gXBN3AfBsOJedow+w==,type:str]
    RESTIC_REST_PASSWORD: ENC[AES256_GCM,data:Sn5uuTT3D1qUGKRsHQrxmNCZ/h97F0/KT6G1+lWTJ5Q=,iv:FrcUyfIz0jJbFgxAOSvEJDhWwajGZ0y12LF7chicK10=,tag:tdUUhkJa6lcC5a3gCJ40ng==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDRxUnpHTHBaL3Ftcm1G
            YVFJZjZCRmExSmZCZm9DNVNwZjJmY2pZL3hjCjNqSlRpMmM2UUF2cmF0VGc1VHVU
            NnpCVElmb2txOTBVdkJIc1JGRndTTjAKLS0tIHptSzlpek9CL2tXemZJOG9GY0k2
            Y1BBekNUNWxZbk94L1MyamJ1T2FqaFkK6rbMoJtXt1ngdH+DtZMTtNhUvZ7ANBCy
            XA9igom5Ur2ZjKxX+3874KkAsqo+NblASZ5fsSyZXZpWhj6It7OqAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T23:21:07Z"
    mac: ENC[AES256_GCM,data:UninwJeU80u47nRB2MOMSWXpd0f0TnpnBkytKQqKLkOGmIrw2EUOdQ32JZU7QyAlfdA5nksW+QEsS+cPcffIE8GtcRYGOob+MaunbUl8w2n99MLkSvH369WNDXMRYsfNRDwoGigCFjkDVt1O6Mm1gzrkRHFcshcJhAfGGEbIKNo=,iv:0MYOJoMLnGt8UWNSe0CjdcC+l/wNAJU/AA9PHewLI7w=,tag:XmDyIhVnuclL/5ldW/SSuw==,type:str]
    encrypted_regex: ^(.*PASSWORD.*|.*SECRET.*|.*TOKEN.*|.*USERNAME.*)$
    version: 3.11.0
