---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@fingol.pro
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:  
      - dns01:
          webhook:
            solverName: hetzner
            groupName: acme.hetzner.com
            config:
              tokenSecretKeyRef:
                name: hetzner-secret
                key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-vpn-fingol-pro
  namespace: traefik-int
spec:
  secretName: letsencrypt-dns-wildcard-cert
  dnsNames:
    - 'vpn.fingol.pro'
    - '*.vpn.fingol.pro'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
