---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default # don't change
  namespace: velero
spec:
  provider: "aws"
  bucket: "velero-int"
  default: true
  config:
    region: "minio"
    s3ForcePathStyle: "true"
    s3Url: "http://truenas.lan:9000"
  credential:
    name: truenas-minio-credentials
    key: cloud
