#
# an example:
#
# cloud: |
#   [default]
#   aws_access_key_id = <your-minio-access-key>
#   aws_secret_access_key = <your-minio-secret-key>
#
apiVersion: v1
kind: Secret
metadata:
    name: truenas-minio-credentials
stringData:
    cloud: ENC[AES256_GCM,data:ucz0AWKwIbS8NDV3gMUt5kOMwHOOwrMlJC/bVHV6cA2V/DSS//NXGt322i17ELZlOLfsU9LsYI6o1XCGrGWCo1pJkHVbJgZlyiZejmXRh70RsPLv2bEpzhygsQh6+tc=,iv:MnlVJqW+Xr58q+fB1RhUV+q4rAxWJ7rzJeTPkGAts+0=,tag:f0IQlwpHCn6dOco6btthTw==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZjd6Y01ZM05mcjVmcnhS
            R0FpRXM4YjhBTFBEQVBISXBNaVdCUHFhUncwCkJKOGlCUW1CNno0dENDc2grN3NZ
            Yy9jMWZmcDNUbnM4aDFKNE4rekZjOHMKLS0tIHdqNm9rcDIvS3hZZHdGWUd3Nllh
            aEtNMnZYamJkL09BTU9PLzgxNnZCdU0KM5BYN6aWHeITjMRFUyBWJWBYG+LbEeAc
            NbHPCPi68/PJMK1O+ycKFBC9UPJxu3ftHyYkXeiFYAc0K+81InpKSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T21:33:43Z"
    mac: ENC[AES256_GCM,data:F1hfINMBwR0P9AlLtuHwZZF68QC82KcUcbir3t4MgX5vNJ7jKbvEA9n/IXhyTw3lCKDpWsuSNxmwrFNB+Z360HOni1bLNci+RKeBTuN1zADy4ltxG9utnOnCqwK0w2CRb9No35sjrsnq2byc//hkC5qrf1SnTwHcCByV4Cyjbd0=,iv:mjtPsFmmxzvIVz8wDR0HPaQO92ZSJwvdsTuctjxwirU=,tag:Nq99eISWzdm+DnQBjov7uw==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
