apiVersion: v1
kind: Secret
metadata:
    name: smb-secret
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:S80rL5xeCA==,iv:pBUU6UleEutnx8TLvs152kkextM82yQXNXBeKHCmSpU=,tag:9kToQIxNjp76IUs3qGH1zw==,type:str]
    password: ENC[AES256_GCM,data:J3YeO7n3Xdk1mAXmu6VHRB/TcBK+sn5Nc2hl4si3VFk=,iv:dkO74P0wZMloerWjEu7C0tXNMV/KE4HaLuGW8+GF7nw=,tag:WmW/ziL39YA72iKRZEpjsg==,type:str]
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N3ZLTzJTSnY5ZEhYRWl1
            M0Z1TTFPWjdxZ1pJUmVvTlp3RVQ0ZTEyWUJJCm52T2FkWUhwcDBKT3U2bm96L0Ux
            R25JYkFqZi93M3c5bWxVYm9ESDBISzAKLS0tIHhlQnFNWU83ZzYrUFo0UTlBTFV1
            aGR5eUxBTDNXTGdxQjI0VkxZZFB6R00KMu/rkyhSDasUIikyVhOkJK5dLjiHjP0V
            HAtdwfZylhI7qEMlj65QpdN8HdTdDk6Cs8ZMW11gvmONnip8+Uxvmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T18:51:57Z"
    mac: ENC[AES256_GCM,data:QvlyUSxLTsa3+dB3y4GHxoAJhhmP1GC3TgI1tzF+xnw6Di53ZOqkOfq6QdPnwT6xANfIKxgi/zWRP92VTD+FkdLbuNnp89MhqlbDLI2t7ZtaOEVKG2kepURzp6TINEWLfZ+8NwAtJ5s3DmFYud+lfl+cN9O12H+AUj+g6gKQnQE=,iv:IgxYc8bfPQqvbLP7VGftAw9gkN6xp4nKK9F2Kj/kbu0=,tag:/bx3jtGnV9/jOkWf9Rx12A==,type:str]
    encrypted_regex: ^(data|stringData|users)$
    version: 3.11.0
