apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  annotations:
    k8up.io/backup: "true"
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: vaultwarden  
spec:
#  storageClassName: nfs-client # Needs to be specified if no default class is set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
