apiVersion: v1
kind: Secret
metadata:
    name: k8up-secret
type: Opaque
stringData:
    username: k3s-int
    password: uRqlCKnqUky4uGKsbBHr2HVxwqCljYAz
sops:
    age:
        - recipient: age1msftgg3vlt9as2r20vmnudgu63hsqxc8fwwp0t63ul3nzezle5rs5lmtvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSDRxUnpHTHBaL3Ftcm1G
            YVFJZjZCRmExSmZCZm9DNVNwZjJmY2pZL3hjCjNqSlRpMmM2UUF2cmF0VGc1VHVU
            NnpCVElmb2txOTBVdkJIc1JGRndTTjAKLS0tIHptSzlpek9CL2tXemZJOG9GY0k2
            Y1BBekNUNWxZbk94L1MyamJ1T2FqaFkK6rbMoJtXt1ngdH+DtZMTtNhUvZ7ANBCy
            XA9igom5Ur2ZjKxX+3874KkAsqo+NblASZ5fsSyZXZpWhj6It7OqAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T23:54:51Z"
    mac: ENC[AES256_GCM,data:TXTwsvVshkoQDHp6a47AvG8GhmBOmax5tExf/HAJWrt/gLtLts0815S2K8IPXkJCki1HMGdBl8h9lRnzUnAbfgNw7NchtLFQRyHDIOEn8JQwJRJJYxFF6YFE5poEFSVO+1//W//W4rylsrv0fegMyeBJaA6jbeX0Oh8JWrYqvHE=,iv:2bU+zjO3TO/R+cW5n9VscztXK/eLmcjIrVs0vzDwRhc=,tag:wYDQUCiStwHQN8+jaZGZmg==,type:str]
    encrypted_regex: ^(.*PASSWORD.*|.*SECRET.*|.*TOKEN.*|.*USERNAME.*)$
    version: 3.11.0
